### PR TITLE
Amend alert banner styles for new markup

### LINKED ISSUE #181: Alter CSS to match new markup in Alert Banner 1.0.0
Alert banner class has changed to `.localgov-alert-banner` so css needs to be updated.
See https://github.com/localgovdrupal/localgov_alert_banner/pull/123

### PR DESCRIPTION
**Pull request by andybroomfield**
Fix #181 
Required for alert banner 1.0.0 release following https://github.com/localgovdrupal/localgov_alert_banner/pull/123

- Change the localgov_alert_banner class to localgov-alert-banner
- Amend the alert sass to account for alert banner markup changes

Not sure if this is actully used, however the sass looked like the old style
alerts, so I've tried to preserve that and add the new classes to alert banner
can be customised from the theme.

### CODE REVIEW

**Review by cjstevens78 — APPROVED** [review]
Looks good to me - i've raised a ticket our end to re-work the croydon theme version of alert.scss.

**Comment by andybroomfield** [comment]
@stephen-cox Why do the tests run `Test LocalGov Drupal Alert Banner`? Is that just mislabbeling?

**Comment by stephen-cox** [comment]
> @stephen-cox Why do the tests run `Test LocalGov Drupal Alert Banner`? Is that just mislabbeling?

Copy and paste error :roll_eyes: Will fix

**Comment by andybroomfield** [comment]
OK, I'm going to merge this one for now.

**Pull request merged**
