### PR TITLE
Add nav-link hover styling with accessible contrast

### LINKED ISSUE #134: Contrast on mega menu during hover state
The colour contrast needs improving on the hover state (on at least the mega menu)

Screenshot 2020-11-20 at 9 55 24 am

### PR DESCRIPTION
**Pull request by paulpopus**
Fixes #134 

This adds class selector with the right specificity so hover and focus states are accessible.

Screenshot from 2021-03-08 16-47-45

Please note there's a [compilation](https://github.com/localgovdrupal/localgov_theme/issues/162) issue right now if you end up testing this PR.

### CODE REVIEW

**Comment by andybroomfield** [comment]
Guess it is better to wait until #164 is merged before reviewing this.

**Comment by paulpopus** [comment]
@andybroomfield #164 has been merged

**Comment by finnlewis** [comment]
@cjstevens78 just reviewing older pull requests. Is this of use or shall we close it?

**Comment by cjstevens78** [comment]
@finnlewis yeah fine to close

**Pull request closed without merging**
