### PR TITLE
1.0.0-alpha2 merge request for new tagged release.

### PR DESCRIPTION
**Pull request by finnlewis**
As discussed, merge request into release branch before tagging. 

In my opinion, this is just a sanity check to confirm the expected commits are going into the release. 

All the merge requests that went into the master branch should already have been peer reviewed, so this could just be a 'lookls good to me' from those in the know.

Happy to hear your thoughts @andybroomfield @cjstevens78 @paulpopus

### CODE REVIEW

**Review by paulpopus — APPROVED** [review]
Looks good to me, I think tests need to be sorted out but that will happen in another issue.

**Review by cjstevens78 — APPROVED** [review]

**Comment by finnlewis** [comment]
It would be nice to see the tests pass, but I would not object to this being merged if urgent.

If we can wait for this to be merged https://github.com/localgovdrupal/localgov_project/pull/24 then we will have the satisfaction of seeing the tests pass before merging.

I realise I ended up creating the PR @cjstevens78 - sorry - which means I should really merge it. But like I say, happy for you to if you need it sooner.

**Comment by finnlewis** [comment]
Oh - actiually, all the tests do pass: OK (74 tests, 1095 assertions)

It's only the PHPO error that's triggering the failure:

```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function DrupalPractice\Sniffs\CodeAnalysis\ScopeInfo::__construct(), 0 passed in /var/www/html/vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1209 and exactly 1 expected in /var/www/html/vendor/drupal/coder/coder_sniffer/DrupalPractice/Sniffs/CodeAnalysis/VariableAnalysisSniff.php:49

**Comment by Adnan-cds** [comment]
> It's only the PHPO error that's triggering the failure:

All good now.  Thanks for promptly dealing with https://github.com/localgovdrupal/localgov_project/pull/24 :)

**Pull request merged**
