### PR TITLE
remove svg fallbacks as obsolete and causing css aggregation to fail

### PR DESCRIPTION
**Pull request by cjstevens78**

### CODE REVIEW

**Comment by Adnan-cds** [comment]
Hi Chris,
Could you please merge the master branch to this branch.  That should update the [test runner file](https://github.com/localgovdrupal/.github/blob/master/workflow-templates/localgov-drupal-ci.yml) leading to test passes.

**Review by Adnan-cds — APPROVED** [review]
Looks good to me know :)

**Comment by Adnan-cds** [comment]
Please merge once Andy has approved it.

FAO @andybroomfield

**Review by andybroomfield — APPROVED** [review]
Quick test shows site fonts working with aggregation.

**Pull request merged**
