### PR TITLE
Determining if the sidebars are empty or not.

### PR DESCRIPTION
**Pull request by Adnan-cds**
Work around for conditional display of theme region.

[Blocks](https://git.drupalcode.org/project/drupal/-/blob/9.0.x/core/modules/block/src/BlockViewBuilder.php#L76) employ [lazy building](https://www.drupal.org/docs/8/api/render-api/auto-placeholdering).  This makes it difficult to determine from **Twig templates** if they will eventually produce [empty content or not](https://github.com/localgovdrupal/localgov_theme/blob/231234f2cb87663dce89445a6a80edf059e4b6bc/templates/system/page.html.twig#L53).

To reproduce this, place any block with **entirely dynamic** content into the sidebar of the localgov_theme (any Views block should do).  It wouldn't show up in the sidebar :(

This work around attempts to get past this limitation by rendering a **copy** of the sidebars' render array in the page preprocess function.  If the rendered markup is nonempty, we can conclude that the sidebar has displayable content.

I am raising this pull request to explain the situation with the [Directory block ticket](https://github.com/localgovdrupal/localgov_directories/issues/30).

### CODE REVIEW

**Comment by finnlewis** [comment]
Thanks @Adnan-cds 

I note that the issue on Drupal.org is 10 years old... and still a bug that cannot be easily solved.

Does this workaround work for you now or is it still casuing issues?

**Comment by Adnan-cds** [comment]
Hi Finn,
The *modified* work around from this pull request works for me.

I stumbled up on this issue when dealing with the "Facets" block (machine id: facet_block:localgov_directories_facets).  If you add it to a Directory channel page's sidebar, it won't appear.  But now we are placing both the Facets block and the [new Directory search block](https://github.com/localgovdrupal/localgov_directories/pull/32) together.  This combination of blocks does **not** suffer from the Drupal core issue possibly because the Directory search block has some content that is rendered prior to lazy building.  So this work around is no longer need for the [Directory search and facet block ticket](https://github.com/localgovdrupal/localgov_directories/issues/30).  But eventually someone will face this issue with another block.  So you will have to decide if you want this fix now or wait until this happens again.

FAO @finnlewis @stephen-cox

**Review by finnlewis — APPROVED** [review]
Looks good to me!

**Comment by Adnan-cds** [comment]
Thanks Finn.  I will merge it in :)

**Pull request merged**
