### PR TITLE
Use the Drupal defined menu for the primary navigation

### LINKED ISSUE #94: Replace the hard coded header with drupal main menu
Currently the menu (option 1 etc) is hard coded, this should either be a region for the menu block, or render the menu directly.

See #61 

Screenshot 2020-10-12 at 5 47 42 pm

### PR DESCRIPTION
**Pull request by andybroomfield**
Fix #94.

This uses the Drupal primary menu for the menu
Also restyles the dropdows to appoximate the main menu style.

### CODE REVIEW

**Comment by andybroomfield** [comment]
Having trouble replicating the service style big dropdown for standard dropdown elements.
Would current be acceptible and then use the megarow expanded section as a region?
Screenshot 2020-10-15 at 9 22 55 pm

**Comment by cjstevens78** [comment]
@andybroomfield I'll pull this into my local tomorrow and take a look - im a bit worried the work involved to get it looking right might take me away from the croydon migration.

**Comment by andybroomfield** [comment]
@cjstevens78 To demo this you need to create a menu under structure -> menu and add its block to the primary and/or secondary menu region. Shouldn't effect your Croydon verison if your overridding the header region template, though you may find it useful to use the technique in your own theme in the future.

**Comment by andybroomfield** [comment]
Screenshot 2020-10-21 at 3 39 47 pm

Thats the current version.
I've completed the templating work, making sure it renders the menu regions.
I had to fiddle with the styles to get it to look right, but since I don't know the css standards being applied, best to let someone with more domain knowledge to pick those up.

**Comment by andybroomfield** [comment]
@cjstevens78 Had to update this branch to avoid merge conflicts, can this be reviewed soonish before more fixes as its getting a awkward to deal with merge conflicts when rebasing from master.

**Review by cjstevens78 — APPROVED** [review]

**Comment by cjstevens78** [comment]
> @cjstevens78 Had to update this branch to avoid merge conflicts, can this be reviewed soonish before more fixes as its getting a awkward to deal with merge conflicts when rebasing from master.

@andybroomfield apologies ! approved

**Comment by andybroomfield** [comment]
Thanks @cjstevens78 :-)

**Pull request merged**
