### PR TITLE
Feature/51 default theme

### PR DESCRIPTION
**Pull request by cjstevens78**
A bunch of theme amends - not including campaigns as these will be on their own ticket #57

### CODE REVIEW

**Review by stephen-cox — APPROVED** [review]
Hi Chris, This largely looks fine to me. I'm not sure that hardcoding all that stuff in footer templates files is a good idea. It would be better to put the content into blocks and menus and just render those, but that will be a development job that can be done later. So looks fine for now.

**Comment by finnlewis** [comment]
@cjstevens78 this was approved by @stephen-cox - are you happy to merge this in?

**Comment by cjstevens78** [comment]
> @cjstevens78 this was approved by @stephen-cox - are you happy to merge this in?

done - sorry completely overlooked the merge!

**Comment by finnlewis** [comment]
Nice one @cjstevens78 - thanks!

**Pull request merged**
